[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [
    "~/.config/alacritty/nordic.toml",
    "~/.config/alacritty/keybinds.toml",
]

[window]
title = "JP Dev Area"
dynamic_title = true
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 150
lines = 80


[cursor.style]
shape = "Beam"

[colors.primary]
background = "#10131c"
foreground = "#bbc2cf"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
